name: "Fan Controller"
description: "Control a fan via the Raspberry Pi's GPIO pins."
version: "0.1.0"
slug: "fan_controller"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
#gpio: true
#privileged:
#  - SYS_RAWIO
full_access: true
